version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - TIDB_URL=${TIDB_URL}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - JIRA_URL=${JIRA_URL}
      - JIRA_USERNAME=${JIRA_USERNAME}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}
    volumes:
      - ./:/app
    command: uvicorn apps.api.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - migrations

  ui:
    build: .
    ports:
      - "8501:8501"
    environment:
      - API_BASE=http://api:8000
    volumes:
      - ./:/app
    command: streamlit run apps/ui/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - api

  migrations:
    build: .
    environment:
      - TIDB_URL=${TIDB_URL}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    volumes:
      - ./:/app
    command: python -m core.db.migrations
    restart: "no"